### ISSUE TITLE
question: it is unclear how to get Webview version

### ISSUE THREAD

**Issue by ParaSpl01t** [NoNameProvided/cordova-plugin-webview-checker#1]
After pasting your code in in javascript file, I do 'cordova build android' and it shows nothing. how can i use it simple to alert the webview version?

**Comment by NoNameProvided** [comment]
Hi! 

You have to install the plugin first with `cordova plugin add cordova-plugin-webview-checker` Then you can call

```js
plugins.webViewChecker.getWebViewVersion()
  .then(function(version) { console.log(version); }))
```

to get the version of the webview.

**Comment by ParaSpl01t** [comment]
Thank you dude, I installed `cordova-plugin-chrome-webview-checker` first. I don't know what i was thinking, my bad. Everything works fine now. And don't you think the code you gave me has a syntax error?

**Comment by NoNameProvided** [comment]
Glad to hear that it working.

> And don't you think the code you gave me has a syntax error?

Has it?
