### ISSUE TITLE
feature: automatically detect WebView implementation on Android 7+

### ISSUE THREAD

**Issue by imgx64** [NoNameProvided/cordova-plugin-webview-checker#2]
On Android 7+, the user can change the WebView implementation. From the [Android 7.0 for Developers](https://developer.android.com/about/versions/nougat/android-7.0.html#webview) page:

> You can choose your WebView provider by enabling Developer Options and selecting **WebView implementation**. You can use any compatible Chrome version (Dev, Beta or Stable) that is installed on your device or the standalone Webview APK to act as the WebView implementation.

This plugin could be more useful if it could detect that the user selected a different implementation, and open the play store for that implementation.

We need this because our users are hitting the [Chrome 53/54 Certificate Transparency bug](https://www.chromium.org/developers/androidwebview/webview-ct-bug). We want to help these users update, but we don't know if we should open the store to the Android System WebView page (com.google.android.webview) or the Chrome page (com.android.chrome).

There's already an Apache-licensed implementation for this in the [ct_workaround project](https://github.com/ntfschr-chromium/ct_workaround/blob/master/app/src/main/java/com/example/android_webview/ct_workaround/WebViewVersionChecker.java).

**Comment by NoNameProvided** [comment]
Thanks, for the report! I already have started to work on this, probably will publish a new version on the weekend.

**Comment by NoNameProvided** [comment]
Hi @imgx64!

This feature is added in the [1.0.0](https://www.npmjs.com/package/cordova-plugin-webview-checker/v/1.0.0) release. You can access the currently selected WebView engine via the `plugins.webViewChecker.getCurrentWebViewPackageInfo()` function. This will return a Promise which resolves to an object like this: 

```ts
{
  packageName: "com.google.android.webview"
  versionName: "69.0.3497.100"
  versionCode: 349710065
}
```

Note: This release contains some minor breaking changes (some function has been renamed).
