### ISSUE TITLE
question: plugins is not defined

### ISSUE THREAD

**Issue by alexislg2** [NoNameProvided/cordova-plugin-webview-checker#3]
Hello,
I get this error. I added the script in the index.html file after all the scripts includes.

    plugins is not defined

Any idea?

**Comment by NoNameProvided** [comment]
Hi! 

I haven't been involved with Cordova development in the last year, so I don't know what could have changed. I am not planning to debug this if you find the root cause and create a PR I will be happy to merge it.

**Comment by rickgbw** [comment]
@alexislg2 is working fine here... Check if your plugin is installed correctly (cordova plugin ls) and if you're including `cordova.js` in your index.html.

**Comment by alexislg2** [comment]
It's working now. I just switched to a new computer... With Cordova you'ld better have many PCs...

**Comment by alexislg2** [comment]
The reason was that I forgot to wait for the DeviceReady signal...
