### ISSUE TITLE
How to replace webview on pre 7.0 devices

### ISSUE THREAD

**Issue by ohenepee** [NoNameProvided/cordova-plugin-webview-checker#5]
Isn't there a way to replace the webview package called by Cordova? That way the Android System WebView that exists on Play Store can be used or called by Cordova.... Its really frustrating to have come to such a stupid crossroad after spending months to develop a cordova app only to realize it doesn't work on pre 7.0 android devices.

**Comment by NoNameProvided** [comment]
This plugin cannot help with that.

If I understand your question correctly you are asking how to replace the used webview implementation by Cordova. I am afraid that can be only done via modifying the Cordova framework itself.

**Comment by ohenepee** [comment]
Actually I knew this plugin couldn't do that. I just wanted to know if you had any know how about how it could be done and if its even possible
