### ISSUE TITLE
Incorrect version published

### ISSUE THREAD

**Issue by WesselWessels** [NoNameProvided/cordova-plugin-webview-checker#6]
The `1.0.0` (latest as of this issue) is released with the wrong version in the plugin.xml file:

```
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0" id="cordova-plugin-webview-checker" version="0.9.2">
```

This throws an error, at least using cordova-android 7.1.1.

To fix, simply release a 1.0.1 version where the versions match in package.json and plugin.xml.

**Comment by NoNameProvided** [comment]
Thanks for the report, I have released 1.0.1.
